# Generated by Django 5.1.1 on 2024-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
