# Generated by Django 5.1.1 on 2024-09-18 06:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4af79ca0-46b2-44a3-8560-60078680ce76'), primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_country_id', models.CharField(max_length=2)),
                ('destination_country_id', models.CharField(max_length=2)),
                ('tracking_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,16}$')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_customer', to='customers.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
